### ISSUE TITLE
Improvement: set numbers in player UI to same size

### ISSUE THREAD

**Issue by juergengenser** [beyondwords-io/player#27]
Suggestion for improving the player UI: in order to avoid varying text widths in the time field while playing the following CSS setting could be applied: `font-variant-numeric: tabular-nums;` - see https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric

**Comment by tuzz** [comment]
Thanks for the suggestion! It is now included in version 0.3.1 of the player.
